export const projects = [
  {
    title: "Recipify — AI-Powered Recipe Builder",
    description:
      "Full-stack mobile app that transforms a photo of your fridge into personalized recipe ideas. Uses GPT Vision to identify ingredients with confidence scores, then generates recipes ranked by match score and filtered by dietary preference (vegan, keto, gluten-free, halal). Features immersive step-by-step cooking mode, automatic shopping list generation for missing ingredients, offline-first persistence, in-app subscriptions via RevenueCat, and full internationalization across 10+ languages. A Vercel serverless proxy keeps API credentials off the client. Deployed via EAS with separate preview and production channels.",
    techStack: [
      "React Native",
      "Expo SDK 55",
      "Expo Router",
      "OpenAI API",
      "Vercel",
      "RevenueCat",
      "i18next",
      "AsyncStorage",
      "TypeScript",
    ],
    githubUrl: null,
    liveUrl: null,
    appStoreUrl:
      "https://apps.apple.com/gb/app/recipify-ai-recipe-scanner/id6765924678",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=co.uk.recipify.app&pcampaignid=web_share",
    featured: true,
  },
  {
    title: "Community Noticeboard — Location-Aware Local Posting Platform",
    description:
      "Cross-platform mobile app giving local residents a digital space to share updates, events, services, and opportunities with their neighbourhood. Location-aware post filtering uses PostGIS spatial queries and postcode-to-coordinate geocoding via OpenCage. Features post creation with category tagging and radius targeting, real-time push notifications for nearby posts via Supabase Edge Functions, a reaction system with aggregated like counts, content reporting, and secure auth with sign-up/sign-in/password reset. Row-Level Security enforces data ownership at the database level with no application-layer gatekeeping required. Automatic cleanup of orphaned media from Supabase Storage. Accessibility-labelled components tested with screen reader tooling.",
    techStack: [
      "React Native",
      "Expo SDK 52",
      "Expo Router",
      "Supabase",
      "PostgreSQL",
      "PostGIS",
      "OpenCage API",
      "React Hook Form",
      "Zod",
      "Jest",
      "TypeScript",
    ],
    githubUrl: null,
    liveUrl: null,
    featured: true,
  },
  {
    title: "SmartLet (Kiado) — Property Rental Marketplace",
    description:
      "Full-stack mobile platform connecting landlords and tenants for short-term and long-term rentals, handling the full rental lifecycle from discovery to payments and compliance. Property search uses Google Places autocomplete, date filtering, and amenity filters. Role-based experience for tenants, landlords, and admins with tailored dashboards. End-to-end booking flow with Stripe-powered payments and automated 6% commission via Stripe Connect. In-app messaging with email fallback via Resend. Landlord earnings dashboard with payout management and booking approval. Tenant protection system with mandatory surveillance device declarations and an in-app abuse reporting workflow. GDPR-compliant account deletion. 17 Supabase Edge Functions handle payments, booking lifecycle automation, push notifications, email dispatch, and admin actions. Turborepo monorepo shares types, the Supabase client, and design tokens across mobile and web.",
    techStack: [
      "React Native",
      "Expo SDK 55",
      "Expo Router",
      "Supabase",
      "PostgreSQL",
      "Stripe Connect",
      "Google Places API",
      "Resend",
      "Zustand",
      "Zod",
      "NativeWind",
      "Sentry",
      "Next.js",
      "Turborepo",
      "TypeScript",
    ],
    githubUrl: null,
    liveUrl: null,
    featured: true,
  },
  {
    title: "Hetényi Tamás Portfolio — Construction Services Website",
    description:
      "Professional portfolio and marketing website for a Hungarian construction contractor specialising in electrical work, plumbing, and flooring. Features an interactive before/after image comparison slider with drag, touch, and keyboard support, and a dynamic gallery with full-screen slideshow and multi-image project support. Password-protected admin panel with drag-and-drop file upload and AWS S3 presigned URL image storage — uploads are handled client-side without exposing credentials. Contact form via EmailJS. NextAuth.js authentication with email/password and Google OAuth. Auto-generated sitemap, OpenGraph metadata, and Hungarian-language SEO for local search visibility.",
    techStack: [
      "Next.js 13",
      "App Router",
      "TypeScript",
      "Tailwind CSS",
      "MongoDB",
      "Mongoose",
      "AWS S3",
      "NextAuth.js",
      "EmailJS",
      "Swiper",
    ],
    githubUrl: null,
    liveUrl: "https://www.hetenyi-bau.hu/",
    featured: false,
  },
  {
    title: "Transfer Learning Investigation",
    description:
      "Machine learning research project investigating transfer learning techniques for image classification. Achieved 95% accuracy improvement over baseline models.",
    techStack: ["Python", "TensorFlow", "Jupyter", "Scikit-learn", "Pandas"],
    githubUrl: null,
    liveUrl: null,
    featured: false,
  },
];
