export const projects = [
  {
    title: "COSMIC — Catalogue of Somatic Mutations in Cancer",
    description:
      "The world's largest curated database of somatic mutations in cancer, built on Next.js 15 and React 19 and used by researchers and clinicians globally. Contributed across the full stack over the lifetime of the project — from the CIS curation module with Elasticsearch-backed paper discovery and multi-file S3 upload flows, to a reusable component library documented in Storybook and CMS-driven layout components. Also designed the secure presigned URL download architecture, built the UploadForm with Zustand-managed state and comprehensive Jest coverage, and created a centralised API client for data fetching and error handling that eliminated repetitive boilerplate across the codebase.",
    techStack: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Zustand",
      "AWS S3",
      "Elasticsearch",
      "Jest",
      "Storybook",
      "NextAuth.js",
      "Docker",
    ],
    githubUrl: null,
    liveUrl: null,
    featured: true,
    type: "professional",
  },
  {
    title: "COSMIC Actionability Curation — Internal Data Management Tool",
    description:
      "Internal full-stack tool built for COSMIC data curators to manage the drug-mutation-disease associations that underpin cancer treatment recommendations. Built end-to-end — the standout feature is a metadata-driven table UI where columns, field types, required indicators, and autocomplete sources are all derived from server-returned metadata, allowing the same interface to adapt dynamically across nine different data tables without code changes. Inline CRUD operations open in a slide-out drawer with pre-populated fields and server action-backed save/delete/clone; a filter and sort system serialises all state into the URL for shareable, browser-navigable pages. Also migrated the state layer from a Context/reducer architecture to Zustand, and added browser close protection to warn curators before unloading with unsaved edits.",
    techStack: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Zustand",
      "REST API",
    ],
    githubUrl: null,
    liveUrl: null,
    featured: true,
    type: "professional",
  },
  {
    title: "CIS — Computational Input System",
    description:
      "REST API backend powering literature ingestion and curation for COSMIC at the Wellcome Sanger Institute — enabling scientists to manage research papers from discovery through to publication-ready curation. Features automated PubMed discovery via scheduled and on-demand queries with background Elasticsearch indexing, two-phase S3 document upload with presigned URL generation and automatic metadata sync, and full-text search across multiple indices. Asynchronous task orchestration runs via Celery Beat with real-time status tracking and a Flower monitoring dashboard, all behind JWT-based auth with role and scope enforcement across a fully async FastAPI service.",
    techStack: [
      "FastAPI",
      "SQLAlchemy",
      "PostgreSQL",
      "Elasticsearch",
      "Celery",
      "Redis",
      "AWS S3",
      "Docker",
      "GitLab CI/CD",
      "Python",
    ],
    githubUrl: null,
    liveUrl: null,
    featured: true,
    type: "professional",
  },
  {
    title: "Recipify — AI-Powered Recipe Builder",
    description:
      "Mobile app that scans a photo of your fridge and generates personalised recipe ideas using GPT Vision, with results ranked by ingredient match score and filtered by dietary preference (vegan, keto, gluten-free, halal, and more). Includes an immersive step-by-step cooking mode, automatic shopping list generation for missing ingredients, offline-first persistence, and full internationalization across 10+ languages. In-app subscriptions are handled via RevenueCat, and a Vercel serverless proxy keeps API credentials off the client.",
    techStack: [
      "React Native",
      "Expo SDK 55",
      "Expo Router",
      "OpenAI API",
      "Vercel",
      "RevenueCat",
      "i18next",
      "TypeScript",
    ],
    githubUrl: null,
    liveUrl: null,
    appStoreUrl:
      "https://apps.apple.com/gb/app/recipify-ai-recipe-scanner/id6765924678",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=co.uk.recipify.app&pcampaignid=web_share",
    featured: true,
    type: "personal",
  },
  {
    title: "Community Noticeboard — Location-Aware Local Posting Platform",
    description:
      "Cross-platform mobile app giving local residents a space to share updates, events, services, and opportunities with their neighbourhood. Location-aware post filtering uses PostGIS spatial queries and OpenCage postcode geocoding, with real-time push notifications dispatched via Supabase Edge Functions for posts within the user's chosen radius. Row-Level Security enforces data ownership at the database level, media cleanup is handled automatically via Supabase Storage hooks, and all components are accessibility-labelled and tested with screen reader tooling.",
    techStack: [
      "React Native",
      "Expo SDK 52",
      "Expo Router",
      "Supabase",
      "PostgreSQL",
      "PostGIS",
      "OpenCage API",
      "Jest",
      "TypeScript",
    ],
    githubUrl: null,
    liveUrl: null,
    featured: true,
    type: "personal",
  },
  {
    title: "SmartLet (Kiado) — Property Rental Marketplace",
    description:
      "Full-stack rental marketplace handling the complete lifecycle from property discovery to payments and compliance, for both short-term and long-term rentals. Role-based dashboards serve tenants, landlords, and admins, with an end-to-end Stripe Connect booking flow featuring automated 6% commission collection and a landlord earnings and payout dashboard. A tenant protection system enforces mandatory surveillance device declarations and an in-app abuse reporting workflow, with 17 Supabase Edge Functions handling payments, notifications, and email dispatch across a Turborepo monorepo.",
    techStack: [
      "React Native",
      "Expo SDK 55",
      "Supabase",
      "Stripe Connect",
      "Zustand",
      "NativeWind",
      "Sentry",
      "Next.js",
      "Turborepo",
      "TypeScript",
    ],
    githubUrl: null,
    liveUrl: null,
    featured: true,
    type: "personal",
  },
  {
    title: "Hétenyi Tamás Portfolio — Construction Services Website",
    description:
      "Marketing website for a Hungarian construction contractor specialising in electrical work, plumbing, and flooring. Features an interactive before/after image comparison slider with drag, touch, and keyboard support, a dynamic project gallery with full-screen slideshow, and a password-protected admin panel with drag-and-drop file upload to AWS S3 via presigned URLs. Authentication is handled by NextAuth.js with Google OAuth, enquiries via EmailJS, and the site is optimised for local search with a Hungarian-language SEO setup, auto-generated sitemap, and OpenGraph metadata.",
    techStack: [
      "Next.js 15",
      "TypeScript",
      "Tailwind CSS",
      "MongoDB",
      "AWS S3",
      "NextAuth.js",
      "EmailJS",
      "Swiper",
    ],
    githubUrl: null,
    liveUrl: "https://www.hetenyi-bau.hu",
    featured: false,
    type: "personal",
  },
];
